
<a href="https://github.com/Shaikats/Python-Assignment" target="_blank" 
   style="display: inline-block; padding: 12px 24px; font-size: 18px; font-weight: bold;
          color: white; background-color: #007BFF; text-decoration: none; 
          border-radius: 8px; transition: all 0.3s ease;">
    🔗 View README & Files
</a>



## **ID: 2215151034**

## **Task 1: Create a 3×3 Matrix of Random Integers between 1 and 50**

In [4]:
import numpy as np

# Generate a 3×3 matrix with random integers between 1 and 50
random_matrix = np.random.randint(1, 51, (3, 3))
print("Random 3×3 Matrix:\n", random_matrix)

Random 3×3 Matrix:
 [[39 27 31]
 [44  5 13]
 [12  8 18]]


## **Task 2: Run the Code with a Fixed Seed (np.random.seed(10))**

In [3]:
# Set seed for reproducibility
np.random.seed(10)

# Generate a 3×3 matrix with random integers between 1 and 50
seeded_matrix = np.random.randint(1, 51, (3, 3))
print("Matrix with Fixed Seed:\n", seeded_matrix)


Matrix with Fixed Seed:
 [[10 37 16]
 [ 1 50 29]
 [26 30 49]]


## **Task 3: Run the Code Without a Seed (Random Values Every Time)**

In [5]:
# No seed set, so values will change each time the code runs
non_seeded_matrix = np.random.randint(1, 51, (3, 3))
print("Matrix Without Seed (Changes Each Run):\n", non_seeded_matrix)

Matrix Without Seed (Changes Each Run):
 [[30 50  9]
 [10  1 43]
 [41 37 17]]


## Explanation of Differences

### With a Fixed Seed (`np.random.seed(10)`)
- The **same matrix** is generated every time the code runs.
- Ensures **consistency**, making it useful for **debugging** and **reproducibility**.
- Helps in research and testing where repeatable results are needed.

### Without a Seed (`np.random.seed(None)`)
- The **matrix values change** each time the code runs.
- Useful for scenarios requiring **unpredictability**, such as **simulations** or **randomized experiments**.
- Provides variation in results, making it ideal for testing different possibilities.